<?php

namespace Tests\Feature;

use App\Traits\TestsTrait;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\User;
use Tests\TestCase;

class DeleteTaskTest extends TestCase
{
    use RefreshDatabase;
    use TestsTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');
    }

    /**
     * A basic test example.
     */
    public function testDeleteTask(): void
    {
        $user = $this->getUser();
        $token = $this->getUserToken($user);
        $task = $this->getOneOfMyTasks($user);
        $response = $this->withHeaders(['Authorization' => "Bearer $token"])
            ->delete("/api/task/$task->id");
        $response
            ->assertStatus(200)
            ->assertJsonStructure([
                'data',
                'message'
            ]);
    }

    public function testDeleteTaskNotMine(): void
    {
        $user = $this->getUser();
        $token = $this->getUserToken($user);
        $taskNotMine = $this->getTaskNotMine($user);
        $response = $this->withHeaders(['Authorization' => "Bearer $token"])
            ->delete("/api/task/$taskNotMine->id");
        $response
            ->assertStatus(404)
            ->assertJsonStructure([
                'data',
                'message'
            ]);
    }
}
