<?php

namespace Tests\Feature;

use App\Traits\TestsTrait;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\User;
use Tests\TestCase;

class ListTaskTest extends TestCase
{
    use RefreshDatabase;
    use TestsTrait;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');

    }

    /**
     * A basic test example.
     */
    public function testListTasks(): void
    {
        $user = $this->getUser();
        $token = $this->getUserToken($user);
        $response = $this->withHeaders([
            'Authorization' => "Bearer $token",
            'Accept'    => 'application/json'
            ])->get('/api/task');
        $response
            ->assertStatus(200)
            ->assertJsonIsArray('data')
            ->assertJsonStructure([
                'data'  => [
                    0 =>[
                        'id',
                        'title',
                        'description',
                        'due_date',
                        'status'
                    ]
                ]
            ]);
    }

    public function testUnauthenticatedListTasks(): void
    {
        $response = $this->withHeader('Accept', 'application/json')->get('/api/task');
        $response
            ->assertStatus(403)
            ->assertJsonStructure([
                'data',
                'message'
            ]);
    }
}
